import os

key = os.urandom(32)

DEBUG=True
MAIL_SERVER='sandbox.smtp.mailtrap.io'
MAIL_PORT=2525
MAIL_USERNAME='e29f3da09656bd'
MAIL_PASSWORD='5564c6f6da2cb0'
MAIL_USE_TLS=True
MAIL_USE_SSL=False
SMS_API_KEY='NPgHgcgx6iO7_FXXGAbknuLwFruvxTtW'
SQLALCHEMY_DATABASE_URI='postgresql://smsuser:smsapp@localhost:5432/smsapp'
SQLALCHEMY_TRACK_MODIFICATIONS=False
MONNIFY_API_KEY='MK_TEST_QD3MYQBZST'
MONNIFY_SECRET_KEY='UTN0TTBN8C8GF1MVEHTUM3UX6ZPBBBE0'
MONNIFY_AUTH_URL='https://sandbox.monnify.com/api/v1/auth/login'
MONNIFY_BASE_URL='https://sandbox.monnify.com'

with open('.env', 'w') as file:
    file.write(
f"SECRET_KEY={key}\nDEBUG={DEBUG}\nSMS_API_KEY={SMS_API_KEY}\nSQLALCHEMY_DATABASE_URI={SQLALCHEMY_DATABASE_URI}\nSQLALCHEMY_TRACK_MODIFICATIONS={SQLALCHEMY_TRACK_MODIFICATIONS}\nMONNIFY_API_KEY={MONNIFY_API_KEY}\nMONNIFY_SECRET_KEY={MONNIFY_SECRET_KEY}\nMONNIFY_AUTH_URL={MONNIFY_AUTH_URL}\nMONNIFY_BASE_URL={MONNIFY_BASE_URL}\nMAIL_SERVER={MAIL_SERVER}\nMAIL_PORT={MAIL_PORT}\nMAIL_USERNAME={MAIL_USERNAME}\nMAIL_PASSWORD={MAIL_PASSWORD}\nMAIL_USE_TLS={MAIL_USE_TLS}\nMAIL_USE_SSL={MAIL_USE_SSL}"

    )
