"""empty message

Revision ID: 1d6bc6d401b4
Revises: 1b84c02ed2cc
Create Date: 2024-06-27 15:56:20.395806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d6bc6d401b4'
down_revision = '1b84c02ed2cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.drop_constraint('user_name_key', type_='unique')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('user_name_key', ['name'])
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('email_verified')
        batch_op.drop_column('fullname')

    # ### end Alembic commands ###
