"""empty message

Revision ID: 7de856135982
Revises: 95d7d5428652
Create Date: 2024-07-06 13:39:26.831896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7de856135982'
down_revision = '95d7d5428652'
branch_labels = None
depends_on = None


def upgrade():
   # Ensure the UUID extension is available
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')

    # Temporarily remove the default value
    op.execute('ALTER TABLE sms ALTER COLUMN id DROP DEFAULT;')

    # Perform the column type alteration with the USING clause
    op.execute('ALTER TABLE sms ALTER COLUMN id TYPE UUID USING (uuid_generate_v4());')

    # Reapply the default value if needed
    op.execute('ALTER TABLE sms ALTER COLUMN id SET DEFAULT uuid_generate_v4();')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
