"""empty message

Revision ID: 95d7d5428652
Revises: cded3dbf253e
Create Date: 2024-07-04 13:45:37.010634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95d7d5428652'
down_revision = 'cded3dbf253e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_reference', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('transaction_reference')

    # ### end Alembic commands ###
